# DO NOT EDIT this file. It is set up in such a way that if you make any edits,
# the test cases may change resulting in a broken local autograder.

# Imports
import sys
import json
import os

os.environ["KMP_DUPLICATE_LIB_OK"] = "True"

from test import Test

from test_rnn import RNNTest
from test_gru import GRUTest
from test_ctc import CTCTest
from test_ctc_decoding import SearchTest

rnn_test = RNNTest()
gru_test = GRUTest()
ctc_test = CTCTest()
search_test = SearchTest()

print("Autograder - v1.1; adopted from CMU Deep Learning class")

test_list = {
    "rnn": [
        {
            "title": "1.1 - RNN Forward",
            "autolab": "1.1 - RNN_Forward",
            "test": [
                rnn_test.test_rnncell_forward,
                ],
            "score": 5,
        },
        {
            "title": "1.2 - RNN Backward",
            "autolab": "1.2 - RNN_Backward",
            "test": [
                rnn_test.test_rnncell_backward,
                ],
            "score": 5,
        },
        {
            "title": "1.3 - RNN Classifier",
            "autolab": "1.3 - RNN_Classifier",
            "test": [
                rnn_test.test_rnn_classifier,
                ],
            "score": 12.5,
        },
    ],
    "gru": [
        {
            "title": "2.1 - GRU Forward",
            "autolab": "2.1 - GRU_Forward",
            "test": [
                gru_test.test_gru_forward,
            ],
            "score": 5,
        },
        {
            "title": "2.2 - GRU Backward",
            "autolab": "GRU_Backward",
            "test": [
                gru_test.test_gru_backward,
            ],
            "score": 15,
        },
        {
            "title": "2.3 - GRU Inference",
            "autolab": "GRU_Inference",
            "test": [
                gru_test.test_gru_inference,
            ],
            "score": 12.5,
        },
    ],
    "ctc": [
        {
            "title": "3.1 - CTC Extend Sequence with Blank",
            "autolab": "Ext_Seq",
            "test": [
                ctc_test.test_ctc_extend_seq,
            ],
            "score": 5,
        },
        {
            "title": "3.2 - CTC Posterior Probability",
            "autolab": "Post_Prob",
            "test": [
                ctc_test.test_ctc_posterior_prob,
            ],
            "score": 5,
        },
        {
            "title": "3.3 - CTC Forward",
            "autolab": "CTC_Forward",
            "test": [
                ctc_test.test_ctc_forward,
            ],
            "score": 10,
        },
        {
            "title": "3.4 - CTC Backward",
            "autolab": "CTC_Backward",
            "test": [
                ctc_test.test_ctc_backward,
            ],
            "score": 5,
        },
    ],
    "search": [
        {
            "title": "4 - CTC Decoding: Greedy Search",
            "autolab": "Greedy",
            "test": [
                search_test.test_greedy_search,
            ],
            "score": 5,
        },
    ],
}


############################################################################################
########################## Test Cases - DO NOT EDIT ########################################
############################################################################################

if __name__ == "__main__":
    # # DO NOT EDIT
    if len(sys.argv) == 1:
        # run all tests
        tests = [test for sublist in test_list.values() for test in sublist]
        pass
    elif len(sys.argv) == 2:
        # run only tests for specified section
        test_type = sys.argv[1]
        if test_type in test_list:
            tests = test_list[test_type]
        else:
            sys.exit(
                "Invalid test type option provided.\nEnter one of [rnn, gru, ctc, search.\nOr leave empty to run all tests.]"
            )

    test = Test()
    for testcase in tests:
        test.run_tests(testcase["title"], [testcase["test"][0]], testcase["score"])
    
    # printing score summary
    print(f' {"_"*42}{"_"*16}')
    print(f'|{"TASK":<42}|{"" :<5}{"SCORE":<10}|')
    print(f'|{"_"*42}|{"_"*15}|')
    for title, score in test.scores.items():
        print(f'|{title:<42}|{"" :<5}{score:<10}|')
        print(f'|{"_"*42}|{"_"*15}|')
    print(f'|{"TOTAL SCORE":<42}|{"" :<5}{test.get_test_scores():<10}|')
    print(f'|{"_"*42}|{"_"*15}|')

    print("\n")
    print(json.dumps({"scores": test.scores}))
